// Test stub for the build-time virtual module "@worker-bundle".
// The real module is generated by esbuild (see esbuild.config.mjs) and embeds
// the worker bundle string. Under vitest the Node DB host never spawns a
// browser worker, so an empty bundle suffices.

export const WORKER_BUNDLE = "";
